// <auto-generated />
using System;
using CasamentoLH_Backend.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CasamentoLH_Backend.Migrations
{
    [DbContext(typeof(CasamentoLHContext))]
    [Migration("20250318005259_CreateGuestGroup")]
    partial class CreateGuestGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CasamentoLH_Backend.Domain.Models.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confirmed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("guest_group_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK____Guest");

                    b.HasIndex("guest_group_id");

                    b.ToTable("tb_guest", (string)null);
                });

            modelBuilder.Entity("CasamentoLH_Backend.Domain.Models.GuestGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK____GuestGroup");

                    b.ToTable("tb_guest_group", (string)null);
                });

            modelBuilder.Entity("CasamentoLH_Backend.Domain.Models.Guest", b =>
                {
                    b.HasOne("CasamentoLH_Backend.Domain.Models.GuestGroup", "GuestGroup")
                        .WithMany("Guests")
                        .HasForeignKey("guest_group_id");

                    b.Navigation("GuestGroup");
                });

            modelBuilder.Entity("CasamentoLH_Backend.Domain.Models.GuestGroup", b =>
                {
                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
